Vagrant.configure("2") do |config|

    config.vm.box = ENV['VAGRANT_BOX'] || "hashicorp/precise64"
    config.vm.box_check_update = false
    
    case ENV['VAGRANT_PROVIDER']
    when "virtualbox"
        config.vm.provider "virtualbox" do |vb|
            vb.memory = ENV["VAGRANT_MEMORY"].to_s || "2048"
            vb.cpus = ENV["VAGRANT_CPUS"].to_s || "2"
        end
    when "vmware_desktop"
        config.vm.provider "vmware_desktop" do |v|
            v.vmx["memsize"] = ENV["VAGRANT_MEMORY"].to_s || "2048"
            v.vmx["numvcpus"] =  ENV["VAGRANT_CPUS"].to_s || "2"
        end
    end
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provision "shell" do |s|

        s.inline = <<-SHELL
            sudo apt-get update
            /bin/bash -c $1
            echo "export CODER_AGENT_TOKEN='$2'" >> /home/vagrant/.bashrc
        SHELL

        s.args = "\"#{ENV["CODER_AGENT_SCRIPT"]}\" #{ENV["CODER_AGENT_TOKEN"]}"
    end

end